### ISSUE TITLE
Does this work on a jetson nano?

### ISSUE THREAD

**Issue by Directory** [polakowo/gpt2bot#3]
The jetson nano is arm A57 which worries me as I've had but luck with libraries supporting arm (especially TensorFlow and PyTorch). Is it compatible? Is cuda supported and what kind of speeds would be expected with the default config but with `turns_memory = -1` and `num_samples = 5`

**Comment by polakowo** [comment]
I can’t think of any issues running it on jetson nano. Cuda is available and enabled by default, but the bot can be deployed on CPU devices as well. It takes a one-two seconds to generate a response without GPU; with GPU a fraction of second; this of course depends on how far the stop token in generated response is. 

I’d definitely rethink setting turns_memory to unlimited since it will slow down generation process with time; values between 2 and 5 are optimal for multi turn-based chat. Number of samples of 5 will further increase processing time (up to 2-3x), and you will have to implement your own logic for selecting the best candidate sample (by default it’s done by random selection)
